apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: c1t3s871t-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-d693cacad8.d74e.p3.openshiftapps.com/rhtap/rhtap-qe:71a393860054e278edcacb3707cdbe0399a61a54@sha256:1d2389a9e4bbbcaa915e455ff95df6e0446f96fe7344b79b7f6fa63cef8625b6
          name: container-image
