apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: c1t3s871t-python-gitops
  description: This is GitOps manifest for c1t3s871t-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: c1t3s871t-python
    backstage.io/kubernetes-id: c1t3s871t-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: c1t3s871t-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:c1t3s871t-python
