apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c1t3s871t-python
  janus-idp.io/tekton: c1t3s871t-python
  backstage.io/kubernetes-id: c1t3s871t-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c1t3s871t-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
